builds:
  -
    main: ./cyberdcli
    binary: cyberdcli
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64


checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'


changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^CI:'
    - Merge pull request


nfpm:
  name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}_{{ .Version }}'
  replacements:
    darwin: macOS
    386: i386
    amd64: x86_64
  homepage:  https://github.com/cybercongress
  description: Distributed search engine
  maintainer: Cyber Admin <cybercongress42@gmail.com>
  license: MIT
  vendor: deepchain
  formats:
    - deb
    - rpm
  dependencies:
    - git
  recommends:
    - rpm


archive:
  name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}_{{ .Version }}'
  replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: zip
  format_overrides:
    - goos: linux
      format: tar.gz
  wrap_in_directory: true
  files:
    - none*