version: '3'

services:
  cybernode0:
    container_name: cybernode0
    image: "cybercongress/cyber"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
    environment:
      - ID=0
      - LOG=${LOG:-deepchain.log}
    volumes:
      - ./build:/deepchain:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  cybernode1:
    container_name: cybernode1
    image: "cybercongress/cyber"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-deepchain.log}
    volumes:
      - ./build:/deepchain:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  cybernode2:
    container_name: cybernode2
    image: "cybercongress/cyber"
    environment:
      - ID=2
      - LOG=${LOG:-deepchain.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/deepchain:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  cybernode3:
    container_name: cybernode3
    image: "cybercongress/cyber"
    environment:
      - ID=3
      - LOG=${LOG:-deepchain.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/deepchain:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

